apiVersion: v1
kind: Service
metadata:
  name: houston-control-plane
  labels:
    app: houston-control-plane
spec:
  type: ClusterIP
  selector:
    app: houston-control-plane
  ports:
    - name: http
      port: 8788
      targetPort: 8788
