apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: houston-system

resources:
  - namespace.yaml
  - rbac.yaml
  - control-plane-deployment.yaml
  - control-plane-service.yaml

commonLabels:
  app.kubernetes.io/part-of: houston-cloud
  app.kubernetes.io/managed-by: kustomize
