apiVersion: v1
kind: ServiceAccount
metadata:
  name: houston-control-plane
  namespace: houston-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: houston-cloud-agent-provisioner
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "create", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "services", "secrets", "endpoints", "pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: houston-control-plane-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: houston-cloud-agent-provisioner
subjects:
  - kind: ServiceAccount
    name: houston-control-plane
    namespace: houston-system
